# =========================
# 1️⃣ 构建阶段（builder）
# =========================
FROM node:20-alpine AS builder

# 替换 Alpine 源为国内镜像源 (阿里云)
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai

WORKDIR /app

# 只拷贝依赖相关文件，利用缓存
COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN apk add --no-cache openssl
RUN npm install

# 拷贝全部源码
COPY . .

# 构建时避免连接真实数据库
ENV DATABASE_URL="file:./dev.db"

RUN npx prisma generate
RUN npm run build


# =========================
# 2️⃣ 运行阶段（runner）
# =========================
FROM node:20-alpine AS runner

# 替换 Alpine 源为国内镜像源 (阿里云)
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai

WORKDIR /app
ENV NODE_ENV=production

RUN apk add --no-cache openssl

# 创建非 root 用户
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# 拷贝构建产物
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma

# 修复 prisma 目录权限，确保 SQLite 可以创建临时文件 (journal/wal)
RUN chown -R nextjs:nodejs prisma

# 上传目录
RUN mkdir -p public/uploads \
 && chown -R nextjs:nodejs public

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
